FROM cpark90/sumo:mosaic_1_16_0

COPY traci_16_update/constants.py /home/sumo/sumo/tools/traci
COPY traci_16_update/connection.py /home/sumo/sumo/tools/traci
COPY traci_16_update/main.py /home/sumo/sumo/tools/traci